### ISSUE TITLE
ModuleNotFoundError: No module named 'models.model_imagenet'

### ISSUE THREAD

**Issue by 2110317008** [Simon4Yan/eSPGAN#3]
root@f2aaf8a01a08:/home/SPGAN-torch/py-spgan# CUDA_VISIBLE_DEVICES=0 python train_spgan.py  --dataset=market2duke --gpu_id=0
Traceback (most recent call last):
  File "train_spgan.py", line 6, in <module>
    import models.models_spgan as models
  File "/home/SPGAN-torch/py-spgan/models/models_spgan.py", line 11, in <module>
    import models.model_imagenet
ModuleNotFoundError: No module named 'models.model_imagenet'
是否是少了一个包叫：model_imagenet
希望能增加readme文件，比如一些包的版本信息数据，存放的格式等等
非常感谢！

**Comment by Simon4Yan** [comment]
Thanks for your question. We don't have to use it, just ignore it.

**Comment by 2110317008** [comment]
问题有点多，但是到我解决到这个问题的时候，实在找不到答案了！
当我run python train_spgan.py  --dataset=market2duke --gpu_id=0 出现下面的情况：
Traceback (most recent call last):
  File "train_spgan.py", line 59, in <module>
    dataset_dirs = utils.reorganize(dataset_dir)
  File "/home/SPGAN-torch/eSPGAN-master/py-spgan/utils/utils.py", line 100, in reorganize
    mkdir(dirs.values())
  File "/home/SPGAN-torch/eSPGAN-master/py-spgan/utils/utils.py", line 17, in mkdir
    if not os.path.isdir(path):
  File "/usr/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not dict_values
希望能得到您的帮助！非常感谢！

**Comment by Simon4Yan** [comment]
Please refer to this project's data format (https://github.com/LynnHo/CycleGAN-Tensorflow-2).
